name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.18']
        otp: ['27', '28']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-deps-
    
    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-mix-build-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('lib/**/*.ex') }}-${{ hashFiles('test/**/*.exs') }}
        restore-keys: |
          ${{ runner.os }}-mix-build-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}-
          ${{ runner.os }}-mix-build-${{ matrix.elixir }}-${{ matrix.otp }}-
    
    - name: Install dependencies
      run: mix deps.get
      env:
        MIX_ENV: test
    
    - name: Compile with warnings as errors
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: test
    
    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test

  format:
    name: Code Formatting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18'
        otp-version: '28'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-deps-
    
    - name: Install dependencies
      run: mix deps.get
      env:
        MIX_ENV: dev
    
    - name: Compile with warnings as errors
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: dev
    
    - name: Check code formatting
      run: mix format --check-formatted
      env:
        MIX_ENV: dev

  credo:
    name: Credo
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18'
        otp-version: '28'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-deps-
    
    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-mix-build-credo-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('lib/**/*.ex') }}
        restore-keys: |
          ${{ runner.os }}-mix-build-credo-${{ hashFiles('**/mix.lock') }}-
          ${{ runner.os }}-mix-build-credo-
    
    - name: Install dependencies
      run: mix deps.get
      env:
        MIX_ENV: dev
    
    - name: Compile with warnings as errors
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: dev
    
    - name: Run Credo
      run: mix credo --strict
      env:
        MIX_ENV: dev

  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18'
        otp-version: '28'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-deps-
    
    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-mix-build-dialyzer-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('lib/**/*.ex') }}
        restore-keys: |
          ${{ runner.os }}-mix-build-dialyzer-${{ hashFiles('**/mix.lock') }}-
          ${{ runner.os }}-mix-build-dialyzer-
    
    - name: Restore PLT cache
      uses: actions/cache@v4
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}-elixir-1.18-otp-28
        restore-keys: |
          ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}-
          ${{ runner.os }}-plt-
    
    - name: Create PLTs dir
      run: mkdir -p priv/plts
    
    - name: Install dependencies
      run: mix deps.get
      env:
        MIX_ENV: dev
    
    - name: Compile with warnings as errors
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: dev
    
    - name: Run Dialyzer
      run: mix dialyzer
      env:
        MIX_ENV: dev